name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker image
        run: |
          docker buildx build -t gaura706/dockerdemo:latest .

      - name: Run Tests
        run: |
          # You can run your tests here, for example:
          mvn test

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for the application to be ready
        run: |
          # Wait for the application to be ready, adjust the timeout as necessary
          sleep 30

      - name: Run Integration Tests
        run: |
          # Run your integration tests here
          curl -f http://localhost:8080/api/posts || exit 1

      - name: Shut down Docker Compose
        run: |
          docker-compose down
